steps:
  #
  # Read variables from CLI
  #
  # -- Project Variables --
  - read: project_name
    prompt: What is the project name?
    default: my_project_name
  - read: company_name
    prompt: What is the company name?
    default: my_company_name

  # -- Color Variables --
  # - read: primary_color
  #   prompt: What is the primary color hex code?
  #   default: "#4f7"
  # - read: secondary_color
  #   prompt: What is the secondary color hex code?
  #   default: "#f74"

  #
  # Write to all template files in the src folder, and
  # index.html. This replaces {{ tmplr.variableName }}
  # with the variables value.
  #
  - update: "src/**/*.tmplr.ts"
  - update: "index.html"
